echo Parsing yaml...
python ./api_yaml.py main.go ./docs/api.yaml

echo Parsing html...
python ./api_html.py ./docs/api.yaml ./docs/api.html

echo Parsing Markdown...
swagger-markdown -i ./docs/api.yaml -o ./docs/api.md
